# Pandas Explode
You may find yourself with a dataset that contains a list of values in a single column. But what you really want is to bring the values from the list into many rows or many columns. So, how do you do that? Using the pandas `.explode()` method and others give you the tools to perform this. For more in depth information about it, you can find it [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html).  

Let's practice the different ways we can using `explode`.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a random array
array = np.random.rand(25, 5).round(decimals=2)
array

array([[0.47, 0.16, 0.77, 0.67, 0.34],
       [0.17, 0.46, 0.57, 0.6 , 0.7 ],
       [0.22, 0.3 , 0.22, 0.84, 0.51],
       [0.66, 0.61, 0.65, 0.64, 0.37],
       [0.  , 0.48, 0.83, 0.99, 0.11],
       [0.6 , 0.21, 0.32, 0.27, 0.6 ],
       [0.81, 0.84, 0.6 , 0.2 , 0.13],
       [0.64, 0.98, 0.56, 0.34, 0.28],
       [0.04, 0.5 , 0.87, 0.7 , 0.2 ],
       [0.2 , 0.27, 0.37, 0.8 , 0.56],
       [0.  , 0.79, 0.66, 0.68, 0.19],
       [0.22, 0.42, 0.47, 0.71, 0.01],
       [0.94, 0.99, 0.83, 0.21, 0.94],
       [0.9 , 0.24, 0.18, 0.56, 0.99],
       [0.76, 0.15, 0.96, 0.51, 0.31],
       [0.58, 0.26, 0.6 , 0.83, 0.64],
       [0.21, 0.25, 0.96, 0.79, 0.68],
       [0.57, 0.26, 0.37, 0.12, 0.05],
       [0.64, 0.28, 0.  , 0.67, 0.08],
       [0.36, 0.17, 0.3 , 0.63, 0.04],
       [0.87, 0.8 , 0.38, 0.81, 0.83],
       [0.58, 0.45, 0.34, 0.29, 0.86],
       [0.7 , 0.  , 0.98, 0.72, 0.95],
       [0.94, 0.52, 0.03, 0.88, 0.72],
       [0.18, 0.97, 0.29, 0.45, 0.62]])

## Explode a list of values into rows

In [3]:
# create dataframe with single column
df = pd.DataFrame({"list_values": array.tolist()})
df.head()

                      list_values
0  [0.47, 0.16, 0.77, 0.67, 0.34]
1    [0.17, 0.46, 0.57, 0.6, 0.7]
2   [0.22, 0.3, 0.22, 0.84, 0.51]
3  [0.66, 0.61, 0.65, 0.64, 0.37]
4   [0.0, 0.48, 0.83, 0.99, 0.11]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   list_values  25 non-null     object
dtypes: object(1)
memory usage: 328.0+ bytes

In [5]:
# each value is a list
type(df.iloc[0][0])

list

In [6]:
# separate list into row with replicating index values
df.explode(column="list_values")

   list_values
0         0.47
0         0.16
0         0.77
0         0.67
0         0.34
..         ...
24        0.18
24        0.97
24        0.29
24        0.45
24        0.62

[125 rows x 1 columns]

## Explode a list of values into columns

In [7]:
# separate list into column by column
pd.DataFrame(df.list_values.values.tolist()).head()

      0     1     2     3     4
0  0.47  0.16  0.77  0.67  0.34
1  0.17  0.46  0.57  0.60  0.70
2  0.22  0.30  0.22  0.84  0.51
3  0.66  0.61  0.65  0.64  0.37
4  0.00  0.48  0.83  0.99  0.11

## Explode a string representation of a list into columns

In [8]:
# now each list is a actually a list of values for each row
df_str = pd.DataFrame({"list_values": [str(a) for a in array.tolist()]})
df_str.head()

                      list_values
0  [0.47, 0.16, 0.77, 0.67, 0.34]
1    [0.17, 0.46, 0.57, 0.6, 0.7]
2   [0.22, 0.3, 0.22, 0.84, 0.51]
3  [0.66, 0.61, 0.65, 0.64, 0.37]
4   [0.0, 0.48, 0.83, 0.99, 0.11]

In [9]:
# each value is a str
type(df_str.iloc[0][0])

str

In [10]:
# This does not work as expected
pd.DataFrame(df_str.list_values.values.tolist()).head()

                                0
0  [0.47, 0.16, 0.77, 0.67, 0.34]
1    [0.17, 0.46, 0.57, 0.6, 0.7]
2   [0.22, 0.3, 0.22, 0.84, 0.51]
3  [0.66, 0.61, 0.65, 0.64, 0.37]
4   [0.0, 0.48, 0.83, 0.99, 0.11]

In [11]:
# One option is to evaluate each string as a list, then proceed as usual
# 'eval' parses and evaluates the string of a list as a python expression
# turning it back into a list
pd.DataFrame(df_str.list_values.apply(lambda u: eval(u)).values.tolist()).head()

      0     1     2     3     4
0  0.47  0.16  0.77  0.67  0.34
1  0.17  0.46  0.57  0.60  0.70
2  0.22  0.30  0.22  0.84  0.51
3  0.66  0.61  0.65  0.64  0.37
4  0.00  0.48  0.83  0.99  0.11